/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAdminAgencesRouteImport } from './routes/_authenticated/admin/agences'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedFinancesIndexRouteImport } from './routes/_authenticated/finances/index'
import { Route as AuthenticatedImmobilierAcquisitionsRouteImport } from './routes/_authenticated/immobilier/acquisitions'
import { Route as AuthenticatedImmobilierInventaireRouteImport } from './routes/_authenticated/immobilier/inventaire'
import { Route as AuthenticatedImmobilierLotissementsRouteImport } from './routes/_authenticated/immobilier/lotissements'
import { Route as AuthenticatedImmobilierParcellesRouteImport } from './routes/_authenticated/immobilier/parcelles'
import { Route as AuthenticatedImmobilierTarifsRouteImport } from './routes/_authenticated/immobilier/tarifs'
import { Route as AuthenticatedVentesSaleIdRouteImport } from './routes/_authenticated/ventes/$saleId'
import { Route as AuthenticatedVentesListeRouteImport } from './routes/_authenticated/ventes/liste'
import { Route as AuthenticatedVentesNouvelleRouteImport } from './routes/_authenticated/ventes/nouvelle'
import { Route as AuthenticatedCrmClientClientIdRouteImport } from './routes/_authenticated/crm/client.$clientId'
import { Route as AuthenticatedImmobilierParcellesPlotIdPrixRouteImport } from './routes/_authenticated/immobilier/parcelles.$plotId.prix'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAgencesRoute =
  AuthenticatedAdminAgencesRouteImport.update({
    id: '/admin/agences',
    path: '/admin/agences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesIndexRoute =
  AuthenticatedFinancesIndexRouteImport.update({
    id: '/finances/',
    path: '/finances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierAcquisitionsRoute =
  AuthenticatedImmobilierAcquisitionsRouteImport.update({
    id: '/immobilier/acquisitions',
    path: '/immobilier/acquisitions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierInventaireRoute =
  AuthenticatedImmobilierInventaireRouteImport.update({
    id: '/immobilier/inventaire',
    path: '/immobilier/inventaire',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierLotissementsRoute =
  AuthenticatedImmobilierLotissementsRouteImport.update({
    id: '/immobilier/lotissements',
    path: '/immobilier/lotissements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierParcellesRoute =
  AuthenticatedImmobilierParcellesRouteImport.update({
    id: '/immobilier/parcelles',
    path: '/immobilier/parcelles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierTarifsRoute =
  AuthenticatedImmobilierTarifsRouteImport.update({
    id: '/immobilier/tarifs',
    path: '/immobilier/tarifs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVentesSaleIdRoute =
  AuthenticatedVentesSaleIdRouteImport.update({
    id: '/ventes/$saleId',
    path: '/ventes/$saleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVentesListeRoute =
  AuthenticatedVentesListeRouteImport.update({
    id: '/ventes/liste',
    path: '/ventes/liste',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVentesNouvelleRoute =
  AuthenticatedVentesNouvelleRouteImport.update({
    id: '/ventes/nouvelle',
    path: '/ventes/nouvelle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmClientClientIdRoute =
  AuthenticatedCrmClientClientIdRouteImport.update({
    id: '/crm/client/$clientId',
    path: '/crm/client/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierParcellesPlotIdPrixRoute =
  AuthenticatedImmobilierParcellesPlotIdPrixRouteImport.update({
    id: '/$plotId/prix',
    path: '/$plotId/prix',
    getParentRoute: () => AuthenticatedImmobilierParcellesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin/agences': typeof AuthenticatedAdminAgencesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/immobilier/acquisitions': typeof AuthenticatedImmobilierAcquisitionsRoute
  '/immobilier/inventaire': typeof AuthenticatedImmobilierInventaireRoute
  '/immobilier/lotissements': typeof AuthenticatedImmobilierLotissementsRoute
  '/immobilier/parcelles': typeof AuthenticatedImmobilierParcellesRouteWithChildren
  '/immobilier/tarifs': typeof AuthenticatedImmobilierTarifsRoute
  '/ventes/$saleId': typeof AuthenticatedVentesSaleIdRoute
  '/ventes/liste': typeof AuthenticatedVentesListeRoute
  '/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/finances/': typeof AuthenticatedFinancesIndexRoute
  '/crm/client/$clientId': typeof AuthenticatedCrmClientClientIdRoute
  '/immobilier/parcelles/$plotId/prix': typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/agences': typeof AuthenticatedAdminAgencesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/immobilier/acquisitions': typeof AuthenticatedImmobilierAcquisitionsRoute
  '/immobilier/inventaire': typeof AuthenticatedImmobilierInventaireRoute
  '/immobilier/lotissements': typeof AuthenticatedImmobilierLotissementsRoute
  '/immobilier/parcelles': typeof AuthenticatedImmobilierParcellesRouteWithChildren
  '/immobilier/tarifs': typeof AuthenticatedImmobilierTarifsRoute
  '/ventes/$saleId': typeof AuthenticatedVentesSaleIdRoute
  '/ventes/liste': typeof AuthenticatedVentesListeRoute
  '/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/finances': typeof AuthenticatedFinancesIndexRoute
  '/crm/client/$clientId': typeof AuthenticatedCrmClientClientIdRoute
  '/immobilier/parcelles/$plotId/prix': typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/agences': typeof AuthenticatedAdminAgencesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/immobilier/acquisitions': typeof AuthenticatedImmobilierAcquisitionsRoute
  '/_authenticated/immobilier/inventaire': typeof AuthenticatedImmobilierInventaireRoute
  '/_authenticated/immobilier/lotissements': typeof AuthenticatedImmobilierLotissementsRoute
  '/_authenticated/immobilier/parcelles': typeof AuthenticatedImmobilierParcellesRouteWithChildren
  '/_authenticated/immobilier/tarifs': typeof AuthenticatedImmobilierTarifsRoute
  '/_authenticated/ventes/$saleId': typeof AuthenticatedVentesSaleIdRoute
  '/_authenticated/ventes/liste': typeof AuthenticatedVentesListeRoute
  '/_authenticated/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/finances/': typeof AuthenticatedFinancesIndexRoute
  '/_authenticated/crm/client/$clientId': typeof AuthenticatedCrmClientClientIdRoute
  '/_authenticated/immobilier/parcelles/$plotId/prix': typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/agences'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/immobilier/acquisitions'
    | '/immobilier/inventaire'
    | '/immobilier/lotissements'
    | '/immobilier/parcelles'
    | '/immobilier/tarifs'
    | '/ventes/$saleId'
    | '/ventes/liste'
    | '/ventes/nouvelle'
    | '/crm/'
    | '/finances/'
    | '/crm/client/$clientId'
    | '/immobilier/parcelles/$plotId/prix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/agences'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/immobilier/acquisitions'
    | '/immobilier/inventaire'
    | '/immobilier/lotissements'
    | '/immobilier/parcelles'
    | '/immobilier/tarifs'
    | '/ventes/$saleId'
    | '/ventes/liste'
    | '/ventes/nouvelle'
    | '/crm'
    | '/finances'
    | '/crm/client/$clientId'
    | '/immobilier/parcelles/$plotId/prix'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/admin/agences'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/immobilier/acquisitions'
    | '/_authenticated/immobilier/inventaire'
    | '/_authenticated/immobilier/lotissements'
    | '/_authenticated/immobilier/parcelles'
    | '/_authenticated/immobilier/tarifs'
    | '/_authenticated/ventes/$saleId'
    | '/_authenticated/ventes/liste'
    | '/_authenticated/ventes/nouvelle'
    | '/_authenticated/crm/'
    | '/_authenticated/finances/'
    | '/_authenticated/crm/client/$clientId'
    | '/_authenticated/immobilier/parcelles/$plotId/prix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/agences': {
      id: '/_authenticated/admin/agences'
      path: '/admin/agences'
      fullPath: '/admin/agences'
      preLoaderRoute: typeof AuthenticatedAdminAgencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/': {
      id: '/_authenticated/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AuthenticatedFinancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/acquisitions': {
      id: '/_authenticated/immobilier/acquisitions'
      path: '/immobilier/acquisitions'
      fullPath: '/immobilier/acquisitions'
      preLoaderRoute: typeof AuthenticatedImmobilierAcquisitionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/inventaire': {
      id: '/_authenticated/immobilier/inventaire'
      path: '/immobilier/inventaire'
      fullPath: '/immobilier/inventaire'
      preLoaderRoute: typeof AuthenticatedImmobilierInventaireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/lotissements': {
      id: '/_authenticated/immobilier/lotissements'
      path: '/immobilier/lotissements'
      fullPath: '/immobilier/lotissements'
      preLoaderRoute: typeof AuthenticatedImmobilierLotissementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/parcelles': {
      id: '/_authenticated/immobilier/parcelles'
      path: '/immobilier/parcelles'
      fullPath: '/immobilier/parcelles'
      preLoaderRoute: typeof AuthenticatedImmobilierParcellesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/tarifs': {
      id: '/_authenticated/immobilier/tarifs'
      path: '/immobilier/tarifs'
      fullPath: '/immobilier/tarifs'
      preLoaderRoute: typeof AuthenticatedImmobilierTarifsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ventes/$saleId': {
      id: '/_authenticated/ventes/$saleId'
      path: '/ventes/$saleId'
      fullPath: '/ventes/$saleId'
      preLoaderRoute: typeof AuthenticatedVentesSaleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ventes/liste': {
      id: '/_authenticated/ventes/liste'
      path: '/ventes/liste'
      fullPath: '/ventes/liste'
      preLoaderRoute: typeof AuthenticatedVentesListeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ventes/nouvelle': {
      id: '/_authenticated/ventes/nouvelle'
      path: '/ventes/nouvelle'
      fullPath: '/ventes/nouvelle'
      preLoaderRoute: typeof AuthenticatedVentesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/client/$clientId': {
      id: '/_authenticated/crm/client/$clientId'
      path: '/crm/client/$clientId'
      fullPath: '/crm/client/$clientId'
      preLoaderRoute: typeof AuthenticatedCrmClientClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/parcelles/$plotId/prix': {
      id: '/_authenticated/immobilier/parcelles/$plotId/prix'
      path: '/$plotId/prix'
      fullPath: '/immobilier/parcelles/$plotId/prix'
      preLoaderRoute: typeof AuthenticatedImmobilierParcellesPlotIdPrixRouteImport
      parentRoute: typeof AuthenticatedImmobilierParcellesRoute
    }
  }
}

interface AuthenticatedImmobilierParcellesRouteChildren {
  AuthenticatedImmobilierParcellesPlotIdPrixRoute: typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}

const AuthenticatedImmobilierParcellesRouteChildren: AuthenticatedImmobilierParcellesRouteChildren =
  {
    AuthenticatedImmobilierParcellesPlotIdPrixRoute:
      AuthenticatedImmobilierParcellesPlotIdPrixRoute,
  }

const AuthenticatedImmobilierParcellesRouteWithChildren =
  AuthenticatedImmobilierParcellesRoute._addFileChildren(
    AuthenticatedImmobilierParcellesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAgencesRoute: typeof AuthenticatedAdminAgencesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedImmobilierAcquisitionsRoute: typeof AuthenticatedImmobilierAcquisitionsRoute
  AuthenticatedImmobilierInventaireRoute: typeof AuthenticatedImmobilierInventaireRoute
  AuthenticatedImmobilierLotissementsRoute: typeof AuthenticatedImmobilierLotissementsRoute
  AuthenticatedImmobilierParcellesRoute: typeof AuthenticatedImmobilierParcellesRouteWithChildren
  AuthenticatedImmobilierTarifsRoute: typeof AuthenticatedImmobilierTarifsRoute
  AuthenticatedVentesSaleIdRoute: typeof AuthenticatedVentesSaleIdRoute
  AuthenticatedVentesListeRoute: typeof AuthenticatedVentesListeRoute
  AuthenticatedVentesNouvelleRoute: typeof AuthenticatedVentesNouvelleRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedFinancesIndexRoute: typeof AuthenticatedFinancesIndexRoute
  AuthenticatedCrmClientClientIdRoute: typeof AuthenticatedCrmClientClientIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAgencesRoute: AuthenticatedAdminAgencesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedImmobilierAcquisitionsRoute:
    AuthenticatedImmobilierAcquisitionsRoute,
  AuthenticatedImmobilierInventaireRoute:
    AuthenticatedImmobilierInventaireRoute,
  AuthenticatedImmobilierLotissementsRoute:
    AuthenticatedImmobilierLotissementsRoute,
  AuthenticatedImmobilierParcellesRoute:
    AuthenticatedImmobilierParcellesRouteWithChildren,
  AuthenticatedImmobilierTarifsRoute: AuthenticatedImmobilierTarifsRoute,
  AuthenticatedVentesSaleIdRoute: AuthenticatedVentesSaleIdRoute,
  AuthenticatedVentesListeRoute: AuthenticatedVentesListeRoute,
  AuthenticatedVentesNouvelleRoute: AuthenticatedVentesNouvelleRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedFinancesIndexRoute: AuthenticatedFinancesIndexRoute,
  AuthenticatedCrmClientClientIdRoute: AuthenticatedCrmClientClientIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
