/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAdminAgencesRouteImport } from './routes/_authenticated/admin/agences'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedCrmClientsRouteImport } from './routes/_authenticated/crm/clients'
import { Route as AuthenticatedCrmVentesRouteImport } from './routes/_authenticated/crm/ventes'
import { Route as AuthenticatedImmobilierAcquisitionsRouteImport } from './routes/_authenticated/immobilier/acquisitions'
import { Route as AuthenticatedImmobilierLotissementsRouteImport } from './routes/_authenticated/immobilier/lotissements'
import { Route as AuthenticatedImmobilierParcellesRouteImport } from './routes/_authenticated/immobilier/parcelles'
import { Route as AuthenticatedImmobilierReservationsRouteImport } from './routes/_authenticated/immobilier/reservations'
import { Route as AuthenticatedImmobilierTarifsRouteImport } from './routes/_authenticated/immobilier/tarifs'
import { Route as AuthenticatedCrmClientClientIdRouteImport } from './routes/_authenticated/crm/client.$clientId'
import { Route as AuthenticatedCrmVentesSaleIdRouteImport } from './routes/_authenticated/crm/ventes.$saleId'
import { Route as AuthenticatedCrmVentesNouveauRouteImport } from './routes/_authenticated/crm/ventes.nouveau'
import { Route as AuthenticatedImmobilierParcellesPlotIdPrixRouteImport } from './routes/_authenticated/immobilier/parcelles.$plotId.prix'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAgencesRoute =
  AuthenticatedAdminAgencesRouteImport.update({
    id: '/admin/agences',
    path: '/admin/agences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmClientsRoute = AuthenticatedCrmClientsRouteImport.update({
  id: '/crm/clients',
  path: '/crm/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmVentesRoute = AuthenticatedCrmVentesRouteImport.update({
  id: '/crm/ventes',
  path: '/crm/ventes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImmobilierAcquisitionsRoute =
  AuthenticatedImmobilierAcquisitionsRouteImport.update({
    id: '/immobilier/acquisitions',
    path: '/immobilier/acquisitions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierLotissementsRoute =
  AuthenticatedImmobilierLotissementsRouteImport.update({
    id: '/immobilier/lotissements',
    path: '/immobilier/lotissements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierParcellesRoute =
  AuthenticatedImmobilierParcellesRouteImport.update({
    id: '/immobilier/parcelles',
    path: '/immobilier/parcelles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierReservationsRoute =
  AuthenticatedImmobilierReservationsRouteImport.update({
    id: '/immobilier/reservations',
    path: '/immobilier/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImmobilierTarifsRoute =
  AuthenticatedImmobilierTarifsRouteImport.update({
    id: '/immobilier/tarifs',
    path: '/immobilier/tarifs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmClientClientIdRoute =
  AuthenticatedCrmClientClientIdRouteImport.update({
    id: '/crm/client/$clientId',
    path: '/crm/client/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmVentesSaleIdRoute =
  AuthenticatedCrmVentesSaleIdRouteImport.update({
    id: '/$saleId',
    path: '/$saleId',
    getParentRoute: () => AuthenticatedCrmVentesRoute,
  } as any)
const AuthenticatedCrmVentesNouveauRoute =
  AuthenticatedCrmVentesNouveauRouteImport.update({
    id: '/nouveau',
    path: '/nouveau',
    getParentRoute: () => AuthenticatedCrmVentesRoute,
  } as any)
const AuthenticatedImmobilierParcellesPlotIdPrixRoute =
  AuthenticatedImmobilierParcellesPlotIdPrixRouteImport.update({
    id: '/$plotId/prix',
    path: '/$plotId/prix',
    getParentRoute: () => AuthenticatedImmobilierParcellesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin/agences': typeof AuthenticatedAdminAgencesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/ventes': typeof AuthenticatedCrmVentesRouteWithChildren
  '/immobilier/acquisitions': typeof AuthenticatedImmobilierAcquisitionsRoute
  '/immobilier/lotissements': typeof AuthenticatedImmobilierLotissementsRoute
  '/immobilier/parcelles': typeof AuthenticatedImmobilierParcellesRouteWithChildren
  '/immobilier/reservations': typeof AuthenticatedImmobilierReservationsRoute
  '/immobilier/tarifs': typeof AuthenticatedImmobilierTarifsRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/crm/client/$clientId': typeof AuthenticatedCrmClientClientIdRoute
  '/crm/ventes/$saleId': typeof AuthenticatedCrmVentesSaleIdRoute
  '/crm/ventes/nouveau': typeof AuthenticatedCrmVentesNouveauRoute
  '/immobilier/parcelles/$plotId/prix': typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/agences': typeof AuthenticatedAdminAgencesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/ventes': typeof AuthenticatedCrmVentesRouteWithChildren
  '/immobilier/acquisitions': typeof AuthenticatedImmobilierAcquisitionsRoute
  '/immobilier/lotissements': typeof AuthenticatedImmobilierLotissementsRoute
  '/immobilier/parcelles': typeof AuthenticatedImmobilierParcellesRouteWithChildren
  '/immobilier/reservations': typeof AuthenticatedImmobilierReservationsRoute
  '/immobilier/tarifs': typeof AuthenticatedImmobilierTarifsRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/crm/client/$clientId': typeof AuthenticatedCrmClientClientIdRoute
  '/crm/ventes/$saleId': typeof AuthenticatedCrmVentesSaleIdRoute
  '/crm/ventes/nouveau': typeof AuthenticatedCrmVentesNouveauRoute
  '/immobilier/parcelles/$plotId/prix': typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/agences': typeof AuthenticatedAdminAgencesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/_authenticated/crm/ventes': typeof AuthenticatedCrmVentesRouteWithChildren
  '/_authenticated/immobilier/acquisitions': typeof AuthenticatedImmobilierAcquisitionsRoute
  '/_authenticated/immobilier/lotissements': typeof AuthenticatedImmobilierLotissementsRoute
  '/_authenticated/immobilier/parcelles': typeof AuthenticatedImmobilierParcellesRouteWithChildren
  '/_authenticated/immobilier/reservations': typeof AuthenticatedImmobilierReservationsRoute
  '/_authenticated/immobilier/tarifs': typeof AuthenticatedImmobilierTarifsRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/crm/client/$clientId': typeof AuthenticatedCrmClientClientIdRoute
  '/_authenticated/crm/ventes/$saleId': typeof AuthenticatedCrmVentesSaleIdRoute
  '/_authenticated/crm/ventes/nouveau': typeof AuthenticatedCrmVentesNouveauRoute
  '/_authenticated/immobilier/parcelles/$plotId/prix': typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/agences'
    | '/admin/audit'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/users'
    | '/crm/clients'
    | '/crm/ventes'
    | '/immobilier/acquisitions'
    | '/immobilier/lotissements'
    | '/immobilier/parcelles'
    | '/immobilier/reservations'
    | '/immobilier/tarifs'
    | '/crm/'
    | '/crm/client/$clientId'
    | '/crm/ventes/$saleId'
    | '/crm/ventes/nouveau'
    | '/immobilier/parcelles/$plotId/prix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/agences'
    | '/admin/audit'
    | '/admin/permissions'
    | '/admin/settings'
    | '/admin/users'
    | '/crm/clients'
    | '/crm/ventes'
    | '/immobilier/acquisitions'
    | '/immobilier/lotissements'
    | '/immobilier/parcelles'
    | '/immobilier/reservations'
    | '/immobilier/tarifs'
    | '/crm'
    | '/crm/client/$clientId'
    | '/crm/ventes/$saleId'
    | '/crm/ventes/nouveau'
    | '/immobilier/parcelles/$plotId/prix'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/admin/agences'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/crm/clients'
    | '/_authenticated/crm/ventes'
    | '/_authenticated/immobilier/acquisitions'
    | '/_authenticated/immobilier/lotissements'
    | '/_authenticated/immobilier/parcelles'
    | '/_authenticated/immobilier/reservations'
    | '/_authenticated/immobilier/tarifs'
    | '/_authenticated/crm/'
    | '/_authenticated/crm/client/$clientId'
    | '/_authenticated/crm/ventes/$saleId'
    | '/_authenticated/crm/ventes/nouveau'
    | '/_authenticated/immobilier/parcelles/$plotId/prix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/agences': {
      id: '/_authenticated/admin/agences'
      path: '/admin/agences'
      fullPath: '/admin/agences'
      preLoaderRoute: typeof AuthenticatedAdminAgencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/clients': {
      id: '/_authenticated/crm/clients'
      path: '/crm/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof AuthenticatedCrmClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/ventes': {
      id: '/_authenticated/crm/ventes'
      path: '/crm/ventes'
      fullPath: '/crm/ventes'
      preLoaderRoute: typeof AuthenticatedCrmVentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/acquisitions': {
      id: '/_authenticated/immobilier/acquisitions'
      path: '/immobilier/acquisitions'
      fullPath: '/immobilier/acquisitions'
      preLoaderRoute: typeof AuthenticatedImmobilierAcquisitionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/lotissements': {
      id: '/_authenticated/immobilier/lotissements'
      path: '/immobilier/lotissements'
      fullPath: '/immobilier/lotissements'
      preLoaderRoute: typeof AuthenticatedImmobilierLotissementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/parcelles': {
      id: '/_authenticated/immobilier/parcelles'
      path: '/immobilier/parcelles'
      fullPath: '/immobilier/parcelles'
      preLoaderRoute: typeof AuthenticatedImmobilierParcellesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/reservations': {
      id: '/_authenticated/immobilier/reservations'
      path: '/immobilier/reservations'
      fullPath: '/immobilier/reservations'
      preLoaderRoute: typeof AuthenticatedImmobilierReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/immobilier/tarifs': {
      id: '/_authenticated/immobilier/tarifs'
      path: '/immobilier/tarifs'
      fullPath: '/immobilier/tarifs'
      preLoaderRoute: typeof AuthenticatedImmobilierTarifsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/client/$clientId': {
      id: '/_authenticated/crm/client/$clientId'
      path: '/crm/client/$clientId'
      fullPath: '/crm/client/$clientId'
      preLoaderRoute: typeof AuthenticatedCrmClientClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/ventes/$saleId': {
      id: '/_authenticated/crm/ventes/$saleId'
      path: '/$saleId'
      fullPath: '/crm/ventes/$saleId'
      preLoaderRoute: typeof AuthenticatedCrmVentesSaleIdRouteImport
      parentRoute: typeof AuthenticatedCrmVentesRoute
    }
    '/_authenticated/crm/ventes/nouveau': {
      id: '/_authenticated/crm/ventes/nouveau'
      path: '/nouveau'
      fullPath: '/crm/ventes/nouveau'
      preLoaderRoute: typeof AuthenticatedCrmVentesNouveauRouteImport
      parentRoute: typeof AuthenticatedCrmVentesRoute
    }
    '/_authenticated/immobilier/parcelles/$plotId/prix': {
      id: '/_authenticated/immobilier/parcelles/$plotId/prix'
      path: '/$plotId/prix'
      fullPath: '/immobilier/parcelles/$plotId/prix'
      preLoaderRoute: typeof AuthenticatedImmobilierParcellesPlotIdPrixRouteImport
      parentRoute: typeof AuthenticatedImmobilierParcellesRoute
    }
  }
}

interface AuthenticatedCrmVentesRouteChildren {
  AuthenticatedCrmVentesSaleIdRoute: typeof AuthenticatedCrmVentesSaleIdRoute
  AuthenticatedCrmVentesNouveauRoute: typeof AuthenticatedCrmVentesNouveauRoute
}

const AuthenticatedCrmVentesRouteChildren: AuthenticatedCrmVentesRouteChildren =
  {
    AuthenticatedCrmVentesSaleIdRoute: AuthenticatedCrmVentesSaleIdRoute,
    AuthenticatedCrmVentesNouveauRoute: AuthenticatedCrmVentesNouveauRoute,
  }

const AuthenticatedCrmVentesRouteWithChildren =
  AuthenticatedCrmVentesRoute._addFileChildren(
    AuthenticatedCrmVentesRouteChildren,
  )

interface AuthenticatedImmobilierParcellesRouteChildren {
  AuthenticatedImmobilierParcellesPlotIdPrixRoute: typeof AuthenticatedImmobilierParcellesPlotIdPrixRoute
}

const AuthenticatedImmobilierParcellesRouteChildren: AuthenticatedImmobilierParcellesRouteChildren =
  {
    AuthenticatedImmobilierParcellesPlotIdPrixRoute:
      AuthenticatedImmobilierParcellesPlotIdPrixRoute,
  }

const AuthenticatedImmobilierParcellesRouteWithChildren =
  AuthenticatedImmobilierParcellesRoute._addFileChildren(
    AuthenticatedImmobilierParcellesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAgencesRoute: typeof AuthenticatedAdminAgencesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCrmClientsRoute: typeof AuthenticatedCrmClientsRoute
  AuthenticatedCrmVentesRoute: typeof AuthenticatedCrmVentesRouteWithChildren
  AuthenticatedImmobilierAcquisitionsRoute: typeof AuthenticatedImmobilierAcquisitionsRoute
  AuthenticatedImmobilierLotissementsRoute: typeof AuthenticatedImmobilierLotissementsRoute
  AuthenticatedImmobilierParcellesRoute: typeof AuthenticatedImmobilierParcellesRouteWithChildren
  AuthenticatedImmobilierReservationsRoute: typeof AuthenticatedImmobilierReservationsRoute
  AuthenticatedImmobilierTarifsRoute: typeof AuthenticatedImmobilierTarifsRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmClientClientIdRoute: typeof AuthenticatedCrmClientClientIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAgencesRoute: AuthenticatedAdminAgencesRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCrmClientsRoute: AuthenticatedCrmClientsRoute,
  AuthenticatedCrmVentesRoute: AuthenticatedCrmVentesRouteWithChildren,
  AuthenticatedImmobilierAcquisitionsRoute:
    AuthenticatedImmobilierAcquisitionsRoute,
  AuthenticatedImmobilierLotissementsRoute:
    AuthenticatedImmobilierLotissementsRoute,
  AuthenticatedImmobilierParcellesRoute:
    AuthenticatedImmobilierParcellesRouteWithChildren,
  AuthenticatedImmobilierReservationsRoute:
    AuthenticatedImmobilierReservationsRoute,
  AuthenticatedImmobilierTarifsRoute: AuthenticatedImmobilierTarifsRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmClientClientIdRoute: AuthenticatedCrmClientClientIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
